on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: Remove sync state file
      run: rm -f .ftp-deploy-sync-state.json
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        # local-dir: ./build/
        # server-dir: ./
        # clean: true  # This will ensure files are replaced
        # overwrite: true # Ensures existing files are replaced with the new ones
       